name: build-and-test

on: [pull_request]

jobs:
  ubuntu:
    name: ${{ matrix.os }}.${{ matrix.compiler }}

    runs-on: ${{ matrix.os }}

    env:
      CXX: ${{ matrix.compiler }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        compiler: [g++-10, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC 10, CMake, Ninja, and GoogleTest.
        run: sudo apt install -y g++-10 cmake ninja-build libgtest-dev

      - name: Generate build files and compilation database.
        run: cmake -B out -G Ninja

      - name: Build unit tests.
        run: ninja -C out

      - name: Run unit tests.
        run: ctest --test-dir out -VV
